package br.com.usp.mac0472.cartografiapaulistana.enums;

public enum EnderecoTitulo {

	ABADE, ACADEMICO, ADVOGADO, AGENTE, AGRICULTOR, AGRIMENSOR, AJUDANTE, ALFERES, ALMIRANTE, APOSTOLO, ARCANJO,
	ARCEBISPO, ARCIPRESTE, ARQUITETA, ARQUITETO, ARQUITETO_PROFESSOR, ASPIRANTE, AVENIDA, AVIADOR, AVIADORA, BACHAREL,
	BANDEIRANTE, BANQUEIRO, BARAO, BARONESA, BEATO, BEATO_PADRE, BEM_AVENTURADO, BENEMERITO, BISPO, BRIGADEIRO, CABO,
	CABO_PM, CADETE, CAMPEADOR, CAPITAO, CAPITAO_ALMIRANTE, CAPITAO_DE_FRAGATA, CAPITAO_DE_MAR_E_GUERRA,
	CAPITAO_GENERAL, CAPITAO_MOR, CAPITAO_PM, CAPITAO_TENENTE, CARDEAL, CARTEIRO, CATEQUISTA, CAVALEIRO, CAVALHEIRO,
	CINEASTA, COMANDANTE, COMEDIANTE, COMENDADOR, COMENDADORA, COMENDADORA_PROFESSORA, COMISSARIA, COMISSARIO,
	COMPOSITOR, CONDE, CONDESSA, CONEGO, CONFRADE, CONSELHEIRO, CONSUL, CORONEL, CORONEL_PM, CORREGEDOR, DELEGADO,
	DENTISTA, DEPUTADA, DEPUTADO, DEPUTADO_DOUTOR, DESEMBARGADOR, DIACONO, DOM, DONA, DOUTOR, DOUTORA, DUQUE, DUQUESA,
	EDITOR, EDUCADOR, EDUCADORA, EMBAIXADOR, EMBAIXADORA, EMPRESARIO, ENGENHEIRO, ENGENHEIRA, ESCOTEIRO, ESCRAVO,
	ESCRITOR, EXPEDICIONARIO, FISICO, FREI, GENERAL, GOVERNADOR, GRUMETE, GUARDA_CIVIL_METROPOLITANO, IMACULADA,
	IMPERATRIZ, INFANTE, INSPETOR, IRMA, IRMAO, IRMAOS, IRMAS, JORNALISTA, LIBERTADOR, LIDER_COMUNITARIO, LIVREIRO,
	LORDE, MADAME, MADRE, MAESTRO, MAJOR, MAJOR_AVIADOR, MAJOR_BRIGADEIRO, MAQUINISTA, MARECHAL, MARECHAL_DO_AR,
	MARQUES, MARQUESA, MERE, MESTRAS, MESTRE, MESTRES, MILITANTE, MINISTRO, MISSIONARIA, MISSIONARIO, MONGE, MONSENHOR,
	MUNICIPAL, MUSICO, NOSSA_SENHORA, NOSSO_SENHOR, OUVIDOR, PADRE, PADRES, PAI, PAPA, PASTOR, PASTORA, PATRIARCA,
	POETA, POETISA, PREFEITO, PRESIDENTE, PRESIDENTE_DA_ACADEMIA_BRASILEIRA_DE_LETRAS, PRESIDENTE_VEREADOR,
	PRIMEIRO_SARGENTO, PRIMEIRO_SARGENTO_PM, PRIMEIRO_TENENTE, PRIMEIRO_TENENTE_PM, PRINCESA, PRINCIPE, PROCURADOR,
	PROFESSOR, PROFESSOR_DOUTOR, PROFESSOR_ENGENHEIRO, PROFESSORA, PROFETA, PROMOTOR, PROVEDOR, PROVEDOR_MOR, RABINO,
	RADIALISTA, RAINHA, REGENTE, REI, REVERENDO, RUA, SACERDOTE, SANTA, SANTO, SAO, SARGENTO, SARGENTO_MOR, SARGENTO_PM,
	SEGUNDO_SARGENTO, SEGUNDO_SARGENTO_PM, SEGUNDO_TENENTE, SENADOR, SENHOR, SENHORA, SERTANISTA, SEU, SINHA, SIR,
	SOCIOLOGO, SOLDADO, SOLDADO_PM, SEROR, SUB_TENENTE, TENENTE, TENENTE_AVIADOR, TENENTE_BRIGADEIRO, TENENTE_CORONEL,
	TEOLOGO, TERCEIRO_SARGENTO, TERCEIRO_SARGENTO_PM, TIA, VEREADOR, VICE_ALMIRANTE, VICE_REI, VIGARIO, VISCONDE,
	VISCONDESSA, VOLUNTARIO, VOLUNTARIOS

}
