package br.com.usp.mac0472.cartografiapaulistana.enums;

public enum EnderecoTipo {

	TRAVESSA, ACESSO, ALAMEDA, AVENIDA, BECO, CAMINHO, COMPLEXO_VIARIO, ESPLANADA, ESTRADA, GALERIA, JARDIM, LADEIRA,
	LARGO, PARQUE, PASSAGEM, PASSARELA, PATIO, PONTE, PRAÇA, RODOVIA, RUA, SERVIDAO, TUNEL, VEREDA, VIA, VIELA, VILA

}
